### ISSUE TITLE
Script is stuck after creating detector for member account in ap-northeast-1 region

### ISSUE THREAD

**Issue by rajesh-bachu** [aws-samples/amazon-guardduty-multiaccount-scripts#18]
Script is stuck after creating detector for member account in ap-northeast-1 region

**Comment by ryanholland** [comment]
This is most often caused by a mismatch on the email address used which causes the invite request to fail validation.  Can you check in your master account for that region in the GuardDuty console, click the Accounts link on the left hand navigation to check the status of the invite.  If the invite did fail due to an incorrect email address ensure you have the root account email in your CSV and double check there are no escape characters in your CSV file as that can also cause issues.
